### ISSUE TITLE
Star Wars Outlaws - Stuck on Gunsmith

### ISSUE THREAD

**Issue by xXProphet92Xx** [dranger003/swo-fixes#3]
please help me, i´m stuck on the Gunsmith.
[20240904_06h12m26s.zip](https://github.com/user-attachments/files/16860704/20240904_06h12m26s.zip)

**Comment by dranger003** [comment]
Here you go.
[20240904_07h42m51s.zip](https://github.com/user-attachments/files/16869700/20240904_07h42m51s.zip)

**Comment by xXProphet92Xx** [comment]
Thanks, it´s work great. Can I ask how you fixed it?

**Comment by dranger003** [comment]
It's a bit involved, but essentially I use CE to revert a couple of memory values. I can probably post the table here, but since it requires special steps I figured it was just easier to do it myself.

**Comment by xXProphet92Xx** [comment]
Thank you very much for the info, think you need to know more precisely which values need to be reset. Then it also depends on the mission. Since these values also change.

I would be interested in taking a look at the table. Maybe someone else can do something with it and create a tool. This would help many.

But I leave this decision to you. It's your work. I already find it very helpful that you sacrifice your time to help other people. The whole thing even free of charge.

**Comment by xXProphet92Xx** [comment]
![IMG_6303](https://github.com/user-attachments/assets/fced9b97-e9c7-48bb-9ba3-13e3811aaa38)
![IMG_6304](https://github.com/user-attachments/assets/02cb46cf-ddd7-4190-8194-fdc2bd8e6378)
![IMG_6305](https://github.com/user-attachments/assets/135826f0-76bf-4acf-b5e7-88618ad1b218)
![IMG_6306](https://github.com/user-attachments/assets/e05dfc6c-5db0-407f-8de1-d01636d273f6)
![IMG_6307](https://github.com/user-attachments/assets/69daed9b-760b-4231-837b-dbbd464db1cf)
![IMG_6308](https://github.com/user-attachments/assets/5a0f479e-5340-4889-9405-78cbc6b592f9)
![IMG_6309](https://github.com/user-attachments/assets/67fb0724-ccd6-48f0-b3aa-6bd36fe576cb)
![IMG_6311](https://github.com/user-attachments/assets/5def4d19-ee4f-4366-b2a1-abc3f6cef3db)
![IMG_6313](https://github.com/user-attachments/assets/4b93119e-1ed3-41bb-8fdf-1d13339f493c)
![IMG_6315](https://github.com/user-attachments/assets/ec358011-0562-461c-aeac-cdf626fed87a)
![IMG_6319](https://github.com/user-attachments/assets/c8754672-b47f-48ad-845c-aab57a45fd52)
![IMG_6320](https://github.com/user-attachments/assets/b81dc90c-43dd-4de9-b3c9-2785e83f4586)
![IMG_6321](https://github.com/user-attachments/assets/3e639a7e-d7c6-4dcb-91ec-2ddb05fa9989)


Now I'm stuck on the mission with the speeder, but I just can't get the hydro-repulsor. The mission goes completely normally but the part isn't installed.

**Comment by xXProphet92Xx** [comment]
[20240906_13h22m36s.zip](https://github.com/user-attachments/files/16907152/20240906_13h22m36s.zip)

**Comment by xXProphet92Xx** [comment]
[06.09.2024.zip](https://github.com/user-attachments/files/16907306/06.09.2024.zip)
This is my complete save game archive since the last fix.

**Comment by dranger003** [comment]
Have you tried using the "easy upgrades" from the previous trainer? I think that might be your solution.

**Comment by xXProphet92Xx** [comment]
Would that be a good idea or would it negate any other progress?

**Comment by dranger003** [comment]
I have all the upgrades installed since day one and the only one that caused and issue was the bolt blaster module on the gunsmith quest. I have not encountered any other issues so far (I am on Tatooine now).

**Comment by xXProphet92Xx** [comment]
Ok

**Comment by xXProphet92Xx** [comment]
Even though I did the mission with the glider, I still can't drive over deep water. Even the Easy Unlock function doesn't help. During the mission itself I was able to drive over deep water, after it never drive over deep water.
![Screenshot 2024-09-07 145841](https://github.com/user-attachments/assets/0af332dd-f4e2-4663-a888-d68ae53d7f38)
![Screenshot 2024-09-07 145854](https://github.com/user-attachments/assets/f8887b04-e673-4144-b8a0-a81a4526c7a0)
![Screenshot 2024-09-07 150123](https://github.com/user-attachments/assets/c614d273-42fd-4df7-a707-124086450763)

**Comment by dranger003** [comment]
That is interesting, I don't have the offset to revert a speeder module as I didn't need it. Are you still stuck? If so then I'll see if I can find a workaround.

**Comment by xXProphet92Xx** [comment]
Yes, I’m still stuck

I'm also in contact with Ubisoft Support, but unfortunately nothing has come of it today, apart from the fact that the bug is known. If I can get a solution at the same time as you that doesn't involve starting the game from the beginning, I'm grateful for any help. But I'm not alone with this, in the forum under cheat happens, there are now two or three people who also have the problem. There are 9 people on Reddit, not many, at least they're posting it online. Older trainer versions don't help either, as they just set all items to 5000.

Here is another video where you can see that I successfully complete the mission, but I don't get the component, just the message that it is installed or unlocked.
https://youtu.be/47RnL3Df9oY?feature=shared

**Comment by xXProphet92Xx** [comment]
I'm also in contact with Ubisoft Support, but unfortunately nothing has come of it today, apart from the fact that the bug is known. If I can get a solution at the same time as you that doesn't involve starting the game from the beginning, I'm grateful for any help. But I'm not alone with this, in the forum under cheat happens, there are now two or three people who also have the problem. There are 9 people on Reddit, not many, at least they're posting it online. Older trainer versions don't help either, as they just set all items to 5000.

**Comment by xXProphet92Xx** [comment]
Here is another video where you can see that I successfully complete the mission, but I don't get the component, just the message that it is installed or unlocked.
https://youtu.be/47RnL3Df9oY?feature=shared

**Comment by dranger003** [comment]
Even though I don't have that bug, I see my save has 6/6 speeder modules unlocked with the Scavenger however when I go to see him, he does not spawn. This isn't blocking me in quests yet and I recall I did go through the quest you have shown in your video and that worked fine for me. I'll try to see if I can revert speeder modules.

**Comment by xXProphet92Xx** [comment]
I managed to complete the mission and fix the bug. I still have a save game from before I landed on the planet. You have to play the first mission with the main base, without invisibility, until you get to Temmin and he installs the mod. After that I was able to successfully drive over water.
![Screenshot 2024-09-13 111615](https://github.com/user-attachments/assets/6f20925a-52ce-44c4-a9d3-d159dcc3adb3)
