### ISSUE TITLE
remove speeder surface repulsor upgrade

### ISSUE THREAD

**Issue by alikhunaizi** [dranger003/swo-fixes#4]
Hello dranger, I hope this finds you well, is there a way to remove the speeder upgrade for riding on water [surface repulsor upgrade], I noticed that I had upgraded it earlier using cheat happen trainer, and I'm afraid later when I reach the mission were I suppose to do the upgrade it will not let me progress.
save file[20240904_18h19m11s.zip](https://github.com/user-attachments/files/16873311/20240904_18h19m11s.zip)

thanks in advance.

**Comment by dranger003** [comment]
I haven't done speeder modules but I'll take a look tonight. Which quest is this for? I don't recall running into that issue on my save.

**Comment by alikhunaizi** [comment]
![Outlaws 9_4_2024 7_58_48 PM](https://github.com/user-attachments/assets/4a38f566-cab6-4673-9b5e-126fb90cdf6e)

i notice my speeder seems to be fully upgraded although I don't recall using the easy upgrade on the speeder,
it is said to drive over deep water you need to acquire an upgrade part during the scavenger mission on akiva
https://gamerant.com/star-wars-outlaws-how-all-speeder-upgrade/

I'm on Akiva but haven't reached that mission yet.

**Comment by dranger003** [comment]
Alright, well once you get to the mission I don't think you will have a problem. Let me know otherwise, I won't spend the time to remove the upgrade until you confirm you need it.

**Comment by alikhunaizi** [comment]
got it, thanks.
